name: Feature Request
description: Suggest an idea for this project
title: "[REQUEST][BOARD][ANDROID version number][KERNEL VERSION]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please describe the software environment you have on the device.
        Examples:
          **Platform:** lena
          **Device:** pdx213 xqbt52 (Xperia 10 III)
          **Kernel version:** 4.19.188-gc7505f2d6045-dirty (due to wlan-qc submodules)
          **Android version:** AOSP11 android-11.0.0_r46
          **Software binaries version:** SW_binaries_for_Xperia_Android_11_4.19_v8a_lena.img
      value: |
        **Platform:**
        **Device:**
        **Kernel version:**
        **Android version:**
        **Software binaries version:**
      render: markdown
    validations:
      required: true
  - type: textarea
    id: describe-feature-request
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
       A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
